"""API routes for Netflix-style collection rows.

Endpoints:
    GET /api/v1/collections  - Home screen themed rows (instant preload, zero timeout)
"""

from __future__ import annotations

import hashlib
import logging
from typing import Any

from fastapi import APIRouter, Depends, Query, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.deps import get_content_router, get_db
from src.api.response import success_envelope
from src.auth.jwt_handler import verify_token
from src.cache.redis_client import redis_client
from src.database.crud.preferences import get_preferences
from src.database.crud.rating import get_ratings_by_user
from src.database.crud.user import get_by_id
from src.database.models.user import User
from src.services.collection_service import CollectionService
from src.services.content_router import ContentRouter
from src.services.content_normalizer import (
    SOURCE_COMIC_VINE,
    SOURCE_GOOGLE_BOOKS,
    SOURCE_INTERNET_ARCHIVE,
)

logger = logging.getLogger(__name__)
router = APIRouter(tags=["collections"])

_bearer = HTTPBearer(auto_error=False)
_TTL_COLLECTIONS_RESPONSE = 60 * 10

# Base verified catalog: pre-baked with verified high-res covers and authors
_CATALOG_SEED: list[dict[str, Any]] = [
    {
        'id': 'seed-1',
        'content_id': 'gb:seed-1',
        'title': 'Dune',
        'author': 'Frank Herbert',
        'cover_url': 'https://covers.openlibrary.org/b/id/11481354-L.jpg',
        'description': 'A science fiction epic set on a desert planet about politics, religion and survival.',
        'genres': ['sci-fi', 'adventure', 'political'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Dune Frank Herbert',
        'published_date': '1965',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-2',
        'content_id': 'gb:seed-2',
        'title': 'Neuromancer',
        'author': 'William Gibson',
        'cover_url': 'https://covers.openlibrary.org/b/id/283860-L.jpg',
        'description': 'Cyberpunk noir set in a dark dystopian future with hackers and AI.',
        'genres': ['sci-fi', 'cyberpunk', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Neuromancer William Gibson',
        'published_date': '1984',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-3',
        'content_id': 'gb:seed-3',
        'title': 'Foundation',
        'author': 'Isaac Asimov',
        'cover_url': 'https://covers.openlibrary.org/b/id/14612610-L.jpg',
        'description': 'The fall of a galactic empire and the plan to preserve knowledge.',
        'genres': ['sci-fi', 'political', 'epic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Foundation Isaac Asimov',
        'published_date': '1951',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-4',
        'content_id': 'gb:seed-4',
        'title': 'The Left Hand of Darkness',
        'author': 'Ursula K. Le Guin',
        'cover_url': 'https://covers.openlibrary.org/b/id/11038837-L.jpg',
        'description': 'An envoy visits a planet where inhabitants have no fixed gender.',
        'genres': ['sci-fi', 'literary', 'philosophical'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Left Hand of Darkness Ursula Le Guin',
        'published_date': '1969',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-5',
        'content_id': 'gb:seed-5',
        'title': 'Hyperion',
        'author': 'Dan Simmons',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780575076372-L.jpg',
        'description': 'Seven pilgrims travel to meet the terrifying Shrike on a distant world.',
        'genres': ['sci-fi', 'horror', 'epic'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Hyperion Dan Simmons',
        'published_date': '1989',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-14',
        'content_id': 'gb:seed-14',
        'title': "The Hitchhiker's Guide to the Galaxy",
        'author': 'Douglas Adams',
        'cover_url': 'https://covers.openlibrary.org/b/id/12986869-L.jpg',
        'description': 'A man is whisked off Earth moments before its demolition for a hyperspace bypass.',
        'genres': ['sci-fi', 'comedy', 'absurdist'],
        'mood': 'funny',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': "Hitchhiker's Guide to the Galaxy Douglas Adams",
        'published_date': '1979',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-20',
        'content_id': 'gb:seed-20',
        'title': "Ender's Game",
        'author': 'Orson Scott Card',
        'cover_url': 'https://covers.openlibrary.org/b/id/12009325-L.jpg',
        'description': 'A child prodigy is trained in a space battle school to fight an alien war.',
        'genres': ['sci-fi', 'adventure', 'military'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': "Ender's Game Orson Scott Card",
        'published_date': '1985',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-21',
        'content_id': 'gb:seed-21',
        'title': 'The Martian',
        'author': 'Andy Weir',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/0804139024-L.jpg',
        'description': 'An astronaut stranded on Mars must use science and wit to survive alone.',
        'genres': ['sci-fi', 'survival', 'comedy'],
        'mood': 'funny',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Martian Andy Weir',
        'published_date': '2011',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-22',
        'content_id': 'gb:seed-22',
        'title': 'Annihilation',
        'author': 'Jeff VanderMeer',
        'cover_url': 'https://covers.openlibrary.org/b/id/8408974-L.jpg',
        'description': 'A team of scientists enters a mysterious forbidden zone where reality breaks down.',
        'genres': ['sci-fi', 'horror', 'mystery'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Annihilation Jeff VanderMeer',
        'published_date': '2014',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-23',
        'content_id': 'gb:seed-23',
        'title': 'Flowers for Algernon',
        'author': 'Daniel Keyes',
        'cover_url': 'https://covers.openlibrary.org/b/id/12947700-L.jpg',
        'description': 'A man with low intelligence undergoes an experiment that transforms his mind.',
        'genres': ['sci-fi', 'literary', 'emotional'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Flowers for Algernon Daniel Keyes',
        'published_date': '1966',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-24',
        'content_id': 'gb:seed-24',
        'title': 'Brave New World',
        'author': 'Aldous Huxley',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/0006545793-L.jpg',
        'description': 'A dystopian society engineered for happiness at the cost of freedom.',
        'genres': ['sci-fi', 'dystopia', 'philosophical'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Brave New World Aldous Huxley',
        'published_date': '1932',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-25',
        'content_id': 'gb:seed-25',
        'title': '1984',
        'author': 'George Orwell',
        'cover_url': 'https://covers.openlibrary.org/b/id/853463-L.jpg',
        'description': 'A man lives under the iron grip of a totalitarian surveillance state.',
        'genres': ['sci-fi', 'dystopia', 'political'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': '1984 George Orwell',
        'published_date': '1949',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-26',
        'content_id': 'gb:seed-26',
        'title': 'The War of the Worlds',
        'author': 'H.G. Wells',
        'cover_url': 'https://covers.openlibrary.org/b/id/36314-L.jpg',
        'description': 'Martians invade Earth and humanity scrambles to survive.',
        'genres': ['sci-fi', 'adventure', 'horror'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The War of the Worlds H G Wells',
        'published_date': '1898',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-27',
        'content_id': 'gb:seed-27',
        'title': 'Solaris',
        'author': 'Stanislaw Lem',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/6586064368-L.jpg',
        'description': 'Scientists studying a mysterious ocean planet find it reflects their deepest fears.',
        'genres': ['sci-fi', 'philosophical', 'literary'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Solaris Stanislaw Lem',
        'published_date': '1961',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-28',
        'content_id': 'gb:seed-28',
        'title': 'Snow Crash',
        'author': 'Neal Stephenson',
        'cover_url': 'https://covers.openlibrary.org/b/id/392508-L.jpg',
        'description': 'A hacker-pizza-delivery-man battles a dangerous new drug in a near-future America.',
        'genres': ['sci-fi', 'cyberpunk', 'action'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Snow Crash Neal Stephenson',
        'published_date': '1992',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-29',
        'content_id': 'gb:seed-29',
        'title': 'The Time Machine',
        'author': 'H.G. Wells',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9786257500937-L.jpg',
        'description': 'A Victorian inventor travels far into the future and finds a strange divided humanity.',
        'genres': ['sci-fi', 'adventure', 'philosophical'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Time Machine H G Wells',
        'published_date': '1895',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-200',
        'content_id': 'gb:seed-200',
        'title': "Childhood's End",
        'author': 'Arthur C. Clarke',
        'cover_url': 'https://books.google.com/books/content?id=6t1cDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        'description': 'Alien overlords usher in a golden age for humanity but at a hidden cost.',
        'genres': ['sci-fi', 'philosophical', 'epic'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': "Childhood's End Arthur C Clarke",
        'published_date': '1953',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-201',
        'content_id': 'gb:seed-201',
        'title': 'Rendezvous with Rama',
        'author': 'Arthur C. Clarke',
        'cover_url': 'https://covers.openlibrary.org/b/id/13472608-L.jpg',
        'description': 'Astronauts explore a vast alien spacecraft drifting through the solar system.',
        'genres': ['sci-fi', 'adventure', 'mystery'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Rendezvous with Rama Arthur C Clarke',
        'published_date': '1973',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-202',
        'content_id': 'gb:seed-202',
        'title': 'The Dispossessed',
        'author': 'Ursula K. Le Guin',
        'cover_url': 'https://covers.openlibrary.org/b/id/6979680-L.jpg',
        'description': 'A physicist travels between two contrasting worlds to unite their societies.',
        'genres': ['sci-fi', 'political', 'philosophical'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Dispossessed Ursula Le Guin',
        'published_date': '1974',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-203',
        'content_id': 'gb:seed-203',
        'title': 'Dark Matter',
        'author': 'Blake Crouch',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/144729758X-L.jpg',
        'description': "A physicist is kidnapped and wakes up in a life that isn't his own.",
        'genres': ['sci-fi', 'thriller', 'mystery'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Dark Matter Blake Crouch',
        'published_date': '2016',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-204',
        'content_id': 'gb:seed-204',
        'title': 'Project Hail Mary',
        'author': 'Andy Weir',
        'cover_url': 'https://covers.openlibrary.org/b/id/11200092-L.jpg',
        'description': 'A lone astronaut must save Earth but first has to remember who he is.',
        'genres': ['sci-fi', 'adventure', 'survival'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Project Hail Mary Andy Weir',
        'published_date': '2021',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-205',
        'content_id': 'gb:seed-205',
        'title': 'The Three-Body Problem',
        'author': 'Liu Cixin',
        'cover_url': 'https://books.google.com/books/content?id=1t1cDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        'description': 'A secret military project sends signals into space with catastrophic consequences.',
        'genres': ['sci-fi', 'political', 'epic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Three-Body Problem Liu Cixin',
        'published_date': '2008',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-206',
        'content_id': 'gb:seed-206',
        'title': 'Blindsight',
        'author': 'Peter Watts',
        'cover_url': 'https://covers.openlibrary.org/b/id/524560-L.jpg',
        'description': 'A crew of posthumans investigates a first contact event at the edge of the solar system.',
        'genres': ['sci-fi', 'horror', 'philosophical'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Blindsight Peter Watts',
        'published_date': '2006',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-207',
        'content_id': 'gb:seed-207',
        'title': "Old Man's War",
        'author': 'John Scalzi',
        'cover_url': 'https://covers.openlibrary.org/b/id/524402-L.jpg',
        'description': 'Elderly people are given young bodies to fight in an interstellar war.',
        'genres': ['sci-fi', 'military', 'adventure'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': "Old Man's War John Scalzi",
        'published_date': '2005',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-9',
        'content_id': 'gb:seed-9',
        'title': 'The Name of the Wind',
        'author': 'Patrick Rothfuss',
        'cover_url': 'https://covers.openlibrary.org/b/id/11480483-L.jpg',
        'description': 'A legendary wizard recounts his extraordinary life story from a quiet inn.',
        'genres': ['fantasy', 'adventure', 'epic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Name of the Wind Patrick Rothfuss',
        'published_date': '2007',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-30',
        'content_id': 'gb:seed-30',
        'title': 'The Way of Kings',
        'author': 'Brandon Sanderson',
        'cover_url': 'https://covers.openlibrary.org/b/id/14658316-L.jpg',
        'description': 'An epic fantasy of war, ancient magic, and the destiny of a broken world.',
        'genres': ['fantasy', 'adventure', 'epic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Way of Kings Brandon Sanderson',
        'published_date': '2010',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-31',
        'content_id': 'gb:seed-31',
        'title': 'A Wizard of Earthsea',
        'author': 'Ursula K. Le Guin',
        'cover_url': 'https://covers.openlibrary.org/b/id/13617691-L.jpg',
        'description': 'A young wizard discovers his true name and the shadow he unleashed on the world.',
        'genres': ['fantasy', 'adventure', 'coming-of-age'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'A Wizard of Earthsea Ursula Le Guin',
        'published_date': '1968',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-32',
        'content_id': 'gb:seed-32',
        'title': 'The Lies of Locke Lamora',
        'author': 'Scott Lynch',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780553804676-L.jpg',
        'description': 'A master thief and con artist runs elaborate schemes in a fantasy city-state.',
        'genres': ['fantasy', 'crime', 'adventure'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Lies of Locke Lamora Scott Lynch',
        'published_date': '2006',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-33',
        'content_id': 'gb:seed-33',
        'title': 'American Gods',
        'author': 'Neil Gaiman',
        'cover_url': 'https://covers.openlibrary.org/b/id/8494659-L.jpg',
        'description': 'Old gods brought to America by immigrants clash with new gods of technology.',
        'genres': ['fantasy', 'mythology', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'American Gods Neil Gaiman',
        'published_date': '2001',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-34',
        'content_id': 'gb:seed-34',
        'title': 'Good Omens',
        'author': 'Terry Pratchett & Neil Gaiman',
        'cover_url': 'https://covers.openlibrary.org/b/id/10482258-L.jpg',
        'description': 'An angel and a demon who have grown fond of Earth conspire to prevent the apocalypse.',
        'genres': ['fantasy', 'comedy', 'adventure'],
        'mood': 'funny',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Good Omens Terry Pratchett Neil Gaiman',
        'published_date': '1990',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-300',
        'content_id': 'gb:seed-300',
        'title': 'The Hobbit',
        'author': 'J.R.R. Tolkien',
        'cover_url': 'https://covers.openlibrary.org/b/id/14627509-L.jpg',
        'description': 'A homebody hobbit is swept into an epic quest to reclaim a dragon-guarded treasure.',
        'genres': ['fantasy', 'adventure', 'classic'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Hobbit J R R Tolkien',
        'published_date': '1937',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-301',
        'content_id': 'gb:seed-301',
        'title': 'A Game of Thrones',
        'author': 'George R.R. Martin',
        'cover_url': 'https://covers.openlibrary.org/b/id/9269962-L.jpg',
        'description': 'Noble families war for control of the Iron Throne while an ancient evil awakens.',
        'genres': ['fantasy', 'political', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'A Game of Thrones George R R Martin',
        'published_date': '1996',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-302',
        'content_id': 'gb:seed-302',
        'title': 'The Blade Itself',
        'author': 'Joe Abercrombie',
        'cover_url': 'https://covers.openlibrary.org/b/id/14543422-L.jpg',
        'description': 'A barbarian, a crippled torturer, and a fading hero are drawn into a vast conspiracy.',
        'genres': ['fantasy', 'dark', 'adventure'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Blade Itself Joe Abercrombie',
        'published_date': '2006',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-303',
        'content_id': 'gb:seed-303',
        'title': 'Mistborn',
        'author': 'Brandon Sanderson',
        'cover_url': 'https://covers.openlibrary.org/b/id/14658160-L.jpg',
        'description': 'A young street thief discovers she has rare powers and joins a heist to overthrow a god-emperor.',
        'genres': ['fantasy', 'adventure', 'epic'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Mistborn Brandon Sanderson',
        'published_date': '2006',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-304',
        'content_id': 'gb:seed-304',
        'title': 'The Colour of Magic',
        'author': 'Terry Pratchett',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/2266211811-L.jpg',
        'description': 'A failed wizard and a naive tourist stumble through a flat world full of absurd magic.',
        'genres': ['fantasy', 'comedy', 'adventure'],
        'mood': 'funny',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Colour of Magic Terry Pratchett',
        'published_date': '1983',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-305',
        'content_id': 'gb:seed-305',
        'title': 'Jonathan Strange and Mr Norrell',
        'author': 'Susanna Clarke',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9789172637894-L.jpg',
        'description': 'Two magicians attempt to restore English magic during the Napoleonic Wars.',
        'genres': ['fantasy', 'historical fiction', 'literary'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Jonathan Strange and Mr Norrell Susanna Clarke',
        'published_date': '2004',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-306',
        'content_id': 'gb:seed-306',
        'title': 'The Night Circus',
        'author': 'Erin Morgenstern',
        'cover_url': 'https://covers.openlibrary.org/b/id/8773134-L.jpg',
        'description': 'Two young magicians are pitted against each other inside a mysterious black and white circus.',
        'genres': ['fantasy', 'romance', 'magical realism'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Night Circus Erin Morgenstern',
        'published_date': '2011',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-307',
        'content_id': 'gb:seed-307',
        'title': 'Piranesi',
        'author': 'Susanna Clarke',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/8417918485-L.jpg',
        'description': 'A man lives in a labyrinthine house filled with statues and tides, losing his memory.',
        'genres': ['fantasy', 'mystery', 'literary'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Piranesi Susanna Clarke',
        'published_date': '2020',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-308',
        'content_id': 'gb:seed-308',
        'title': 'His Dark Materials',
        'author': 'Philip Pullman',
        'cover_url': 'https://covers.openlibrary.org/b/id/8747028-L.jpg',
        'description': 'A girl with a truth-telling compass crosses parallel worlds to save humanity.',
        'genres': ['fantasy', 'adventure', 'philosophical'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'His Dark Materials Philip Pullman',
        'published_date': '1995',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-309',
        'content_id': 'gb:seed-309',
        'title': 'The Priory of the Orange Tree',
        'author': 'Samantha Shannon',
        'cover_url': 'https://covers.openlibrary.org/b/id/8802446-L.jpg',
        'description': 'A queendom without an heir, a dragon threat, and three women at the center of it all.',
        'genres': ['fantasy', 'epic', 'adventure'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Priory of the Orange Tree Samantha Shannon',
        'published_date': '2019',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-10',
        'content_id': 'gb:seed-10',
        'title': 'Kafka on the Shore',
        'author': 'Haruki Murakami',
        'cover_url': 'https://covers.openlibrary.org/b/id/4982600-L.jpg',
        'description': 'A surreal journey of a runaway boy and an old man who can talk to cats.',
        'genres': ['literary', 'magical realism', 'philosophical'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Kafka on the Shore Haruki Murakami',
        'published_date': '2002',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-11',
        'content_id': 'gb:seed-11',
        'title': 'The Road',
        'author': 'Cormac McCarthy',
        'cover_url': 'https://covers.openlibrary.org/b/id/198120-L.jpg',
        'description': 'A father and son walk through a burned America trying to stay alive and human.',
        'genres': ['literary', 'post-apocalyptic', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Road Cormac McCarthy',
        'published_date': '2006',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-15',
        'content_id': 'gb:seed-15',
        'title': 'Beloved',
        'author': 'Toni Morrison',
        'cover_url': 'https://covers.openlibrary.org/b/id/8261367-L.jpg',
        'description': 'A former enslaved woman is haunted by the ghost of her dead daughter.',
        'genres': ['literary', 'historical fiction', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Beloved Toni Morrison',
        'published_date': '1987',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-40',
        'content_id': 'gb:seed-40',
        'title': 'Never Let Me Go',
        'author': 'Kazuo Ishiguro',
        'cover_url': 'https://covers.openlibrary.org/b/id/1047334-L.jpg',
        'description': 'Students at a quiet English boarding school face an unthinkable predetermined fate.',
        'genres': ['literary', 'sci-fi', 'emotional'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Never Let Me Go Kazuo Ishiguro',
        'published_date': '2005',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-41',
        'content_id': 'gb:seed-41',
        'title': 'Crime and Punishment',
        'author': 'Fyodor Dostoevsky',
        'cover_url': 'https://covers.openlibrary.org/b/id/10040573-L.jpg',
        'description': 'A destitute student murders a pawnbroker and is consumed by guilt and paranoia.',
        'genres': ['literary', 'crime', 'philosophical'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Crime and Punishment Dostoevsky',
        'published_date': '1866',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-42',
        'content_id': 'gb:seed-42',
        'title': 'One Hundred Years of Solitude',
        'author': 'Gabriel Garcia Marquez',
        'cover_url': 'https://covers.openlibrary.org/b/id/12627383-L.jpg',
        'description': 'Seven generations of the Buendía family in the mythical town of Macondo.',
        'genres': ['literary', 'magical realism', 'epic'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'One Hundred Years of Solitude Gabriel Garcia Marquez',
        'published_date': '1967',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-43',
        'content_id': 'gb:seed-43',
        'title': 'The Great Gatsby',
        'author': 'F. Scott Fitzgerald',
        'cover_url': 'https://covers.openlibrary.org/b/id/10590366-L.jpg',
        'description': 'The mysterious millionaire Jay Gatsby chases his lost love in Jazz Age New York.',
        'genres': ['literary', 'romance', 'classic'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Great Gatsby F Scott Fitzgerald',
        'published_date': '1925',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-400',
        'content_id': 'gb:seed-400',
        'title': 'Norwegian Wood',
        'author': 'Haruki Murakami',
        'cover_url': 'https://covers.openlibrary.org/b/id/13613167-L.jpg',
        'description': 'A young man in Tokyo mourns the death of his best friend and falls in love.',
        'genres': ['literary', 'romance', 'coming-of-age'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Norwegian Wood Haruki Murakami',
        'published_date': '1987',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-401',
        'content_id': 'gb:seed-401',
        'title': 'The Remains of the Day',
        'author': 'Kazuo Ishiguro',
        'cover_url': 'https://covers.openlibrary.org/b/id/95742-L.jpg',
        'description': 'An English butler reflects on decades of service and a life of missed chances.',
        'genres': ['literary', 'historical fiction', 'emotional'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Remains of the Day Kazuo Ishiguro',
        'published_date': '1989',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-402',
        'content_id': 'gb:seed-402',
        'title': 'Middlemarch',
        'author': 'George Eliot',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780563394020-L.jpg',
        'description': 'Interlocking lives in a provincial English town reveal the cost of ambition and love.',
        'genres': ['literary', 'romance', 'classic'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Middlemarch George Eliot',
        'published_date': '1871',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-403',
        'content_id': 'gb:seed-403',
        'title': 'To Kill a Mockingbird',
        'author': 'Harper Lee',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/0062877798-L.jpg',
        'description': 'A lawyer defends a Black man in the American South while his children watch.',
        'genres': ['literary', 'historical fiction', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'To Kill a Mockingbird Harper Lee',
        'published_date': '1960',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-404',
        'content_id': 'gb:seed-404',
        'title': 'The Catcher in the Rye',
        'author': 'J.D. Salinger',
        'cover_url': 'https://covers.openlibrary.org/b/id/9273490-L.jpg',
        'description': 'A disillusioned teenager wanders New York after being expelled from school.',
        'genres': ['literary', 'coming-of-age', 'classic'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Catcher in the Rye J D Salinger',
        'published_date': '1951',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-405',
        'content_id': 'gb:seed-405',
        'title': 'Lolita',
        'author': 'Vladimir Nabokov',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9783538053595-L.jpg',
        'description': 'A middle-aged professor becomes obsessed with a twelve-year-old girl.',
        'genres': ['literary', 'dark', 'controversial'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Lolita Vladimir Nabokov',
        'published_date': '1955',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-406',
        'content_id': 'gb:seed-406',
        'title': 'Things Fall Apart',
        'author': 'Chinua Achebe',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9782266264-L.jpg',
        'description': 'A proud Nigerian warrior watches his traditional world collapse under colonialism.',
        'genres': ['literary', 'historical fiction', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Things Fall Apart Chinua Achebe',
        'published_date': '1958',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-407',
        'content_id': 'gb:seed-407',
        'title': 'The Alchemist',
        'author': 'Paulo Coelho',
        'cover_url': 'https://covers.openlibrary.org/b/id/7414780-L.jpg',
        'description': 'A shepherd boy travels from Spain to Egypt in search of a worldly treasure.',
        'genres': ['literary', 'philosophical', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Alchemist Paulo Coelho',
        'published_date': '1988',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-408',
        'content_id': 'gb:seed-408',
        'title': 'Siddhartha',
        'author': 'Hermann Hesse',
        'cover_url': 'https://covers.openlibrary.org/b/id/6562535-L.jpg',
        'description': 'A young Indian man seeks enlightenment through teachers, love, and river life.',
        'genres': ['literary', 'philosophical', 'spiritual'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Siddhartha Hermann Hesse',
        'published_date': '1922',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-50',
        'content_id': 'gb:seed-50',
        'title': 'The Girl with the Dragon Tattoo',
        'author': 'Stieg Larsson',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/0857054104-L.jpg',
        'description': "A disgraced journalist and a hacker investigate a wealthy family's dark secrets.",
        'genres': ['thriller', 'mystery', 'crime'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Girl with the Dragon Tattoo Stieg Larsson',
        'published_date': '2005',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-51',
        'content_id': 'gb:seed-51',
        'title': 'Gone Girl',
        'author': 'Gillian Flynn',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9789000914135-L.jpg',
        'description': 'A woman vanishes on her wedding anniversary and her husband becomes the suspect.',
        'genres': ['thriller', 'mystery', 'dark'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Gone Girl Gillian Flynn',
        'published_date': '2012',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-52',
        'content_id': 'gb:seed-52',
        'title': 'And Then There Were None',
        'author': 'Agatha Christie',
        'cover_url': 'https://covers.openlibrary.org/b/id/11172296-L.jpg',
        'description': 'Ten strangers lured to an island are murdered one by one by an unseen killer.',
        'genres': ['mystery', 'thriller', 'classic'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'And Then There Were None Agatha Christie',
        'published_date': '1939',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-53',
        'content_id': 'gb:seed-53',
        'title': 'In the Woods',
        'author': 'Tana French',
        'cover_url': 'https://covers.openlibrary.org/b/id/1474730-L.jpg',
        'description': 'A Dublin detective investigates a murder site where children vanished decades ago.',
        'genres': ['mystery', 'thriller', 'literary'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'In the Woods Tana French',
        'published_date': '2007',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-500',
        'content_id': 'gb:seed-500',
        'title': 'Big Little Lies',
        'author': 'Liane Moriarty',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781405931564-L.jpg',
        'description': 'Three women in a wealthy seaside town share a secret that ends in murder.',
        'genres': ['thriller', 'mystery', 'drama'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Big Little Lies Liane Moriarty',
        'published_date': '2014',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-501',
        'content_id': 'gb:seed-501',
        'title': 'The Silent Patient',
        'author': 'Alex Michaelides',
        'cover_url': 'https://covers.openlibrary.org/b/id/9407338-L.jpg',
        'description': 'A famous painter shoots her husband then never speaks again.',
        'genres': ['thriller', 'mystery', 'psychological'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Silent Patient Alex Michaelides',
        'published_date': '2019',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-502',
        'content_id': 'gb:seed-502',
        'title': 'Sharp Objects',
        'author': 'Gillian Flynn',
        'cover_url': 'https://covers.openlibrary.org/b/id/167973-L.jpg',
        'description': "A journalist returns to her hometown to investigate two girls' murders.",
        'genres': ['thriller', 'mystery', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Sharp Objects Gillian Flynn',
        'published_date': '2006',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-503',
        'content_id': 'gb:seed-503',
        'title': 'The Da Vinci Code',
        'author': 'Dan Brown',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9788408175728-L.jpg',
        'description': 'A symbologist races to solve a murder inside the Louvre involving a secret society.',
        'genres': ['thriller', 'mystery', 'adventure'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Da Vinci Code Dan Brown',
        'published_date': '2003',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-504',
        'content_id': 'gb:seed-504',
        'title': 'Rebecca',
        'author': 'Daphne du Maurier',
        'cover_url': 'https://covers.openlibrary.org/b/id/8238729-L.jpg',
        'description': "A young bride is haunted by the memory of her husband's first wife.",
        'genres': ['mystery', 'gothic', 'romance'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Rebecca Daphne du Maurier',
        'published_date': '1938',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-505',
        'content_id': 'gb:seed-505',
        'title': 'The Woman in White',
        'author': 'Wilkie Collins',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9780140430967-L.jpg',
        'description': 'A drawing teacher uncovers a sinister conspiracy involving a mysterious woman.',
        'genres': ['mystery', 'thriller', 'classic'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Woman in White Wilkie Collins',
        'published_date': '1859',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-506',
        'content_id': 'gb:seed-506',
        'title': 'Tinker Tailor Soldier Spy',
        'author': 'John le Carré',
        'cover_url': 'https://covers.openlibrary.org/b/id/7021556-L.jpg',
        'description': 'A retired spy is brought back to find a Soviet mole at the top of British intelligence.',
        'genres': ['thriller', 'spy', 'mystery'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Tinker Tailor Soldier Spy John le Carre',
        'published_date': '1974',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-507',
        'content_id': 'gb:seed-507',
        'title': 'The Girl on the Train',
        'author': 'Paula Hawkins',
        'cover_url': 'https://covers.openlibrary.org/b/id/7350360-L.jpg',
        'description': 'A troubled woman becomes obsessed with a couple she watches from her train window.',
        'genres': ['thriller', 'mystery', 'psychological'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Girl on the Train Paula Hawkins',
        'published_date': '2015',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-60',
        'content_id': 'gb:seed-60',
        'title': 'Jane Eyre',
        'author': 'Charlotte Brontë',
        'cover_url': 'https://covers.openlibrary.org/b/id/12521151-M.jpg',
        'description': 'An orphan governess falls for the brooding, secretive Mr Rochester.',
        'genres': ['romance', 'gothic', 'classic'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Jane Eyre Charlotte Bronte',
        'published_date': '1847',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-61',
        'content_id': 'gb:seed-61',
        'title': 'Outlander',
        'author': 'Diana Gabaldon',
        'cover_url': 'https://covers.openlibrary.org/b/id/14428230-L.jpg',
        'description': 'A World War II nurse is swept back to 18th century Scotland and falls for a warrior.',
        'genres': ['romance', 'historical fiction', 'adventure'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Outlander Diana Gabaldon',
        'published_date': '1991',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-62',
        'content_id': 'gb:seed-62',
        'title': 'The Notebook',
        'author': 'Nicholas Sparks',
        'cover_url': 'https://covers.openlibrary.org/b/id/7382153-L.jpg',
        'description': 'A summer romance between two people from different worlds spans decades.',
        'genres': ['romance', 'drama'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Notebook Nicholas Sparks',
        'published_date': '1996',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-600',
        'content_id': 'gb:seed-600',
        'title': 'Wuthering Heights',
        'author': 'Emily Brontë',
        'cover_url': 'https://covers.openlibrary.org/b/id/12521183-M.jpg',
        'description': 'A doomed love between a wild foundling and a headstrong girl tears two families apart.',
        'genres': ['romance', 'gothic', 'classic'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Wuthering Heights Emily Bronte',
        'published_date': '1847',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-601',
        'content_id': 'gb:seed-601',
        'title': 'Anna Karenina',
        'author': 'Leo Tolstoy',
        'cover_url': 'https://covers.openlibrary.org/b/id/2560652-L.jpg',
        'description': 'A Russian aristocrat risks everything for a passionate but destructive love affair.',
        'genres': ['romance', 'literary', 'classic'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Anna Karenina Leo Tolstoy',
        'published_date': '1878',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-602',
        'content_id': 'gb:seed-602',
        'title': 'Me Before You',
        'author': 'Jojo Moyes',
        'cover_url': 'https://covers.openlibrary.org/b/id/14419339-L.jpg',
        'description': 'A quirky young woman becomes the carer of a paralysed man who changes her life.',
        'genres': ['romance', 'drama', 'emotional'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Me Before You Jojo Moyes',
        'published_date': '2012',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-603',
        'content_id': 'gb:seed-603',
        'title': 'The Fault in Our Stars',
        'author': 'John Green',
        'cover_url': 'https://covers.openlibrary.org/b/id/7418786-L.jpg',
        'description': 'Two teenagers with cancer fall in love at a support group.',
        'genres': ['romance', 'coming-of-age', 'emotional'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Fault in Our Stars John Green',
        'published_date': '2012',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-604',
        'content_id': 'gb:seed-604',
        'title': 'Atonement',
        'author': 'Ian McEwan',
        'cover_url': 'https://covers.openlibrary.org/b/id/8381043-L.jpg',
        'description': "A thirteen-year-old's lie tears apart two lovers and haunts her for the rest of her life.",
        'genres': ['romance', 'literary', 'historical fiction'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Atonement Ian McEwan',
        'published_date': '2001',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-605',
        'content_id': 'gb:seed-605',
        'title': 'The Bronze Horseman',
        'author': 'Paullina Simons',
        'cover_url': 'https://covers.openlibrary.org/b/id/6822636-L.jpg',
        'description': 'Two young people fall in love in Leningrad during World War II.',
        'genres': ['romance', 'historical fiction', 'war'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Bronze Horseman Paullina Simons',
        'published_date': '2000',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-80',
        'content_id': 'gb:seed-80',
        'title': 'It',
        'author': 'Stephen King',
        'cover_url': 'https://covers.openlibrary.org/b/id/8569284-L.jpg',
        'description': 'A shapeshifting evil preys on children in a small Maine town across two timelines.',
        'genres': ['horror', 'adventure', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'It Stephen King',
        'published_date': '1986',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-81',
        'content_id': 'gb:seed-81',
        'title': 'House of Leaves',
        'author': 'Mark Z. Danielewski',
        'cover_url': 'https://covers.openlibrary.org/b/id/6450442-L.jpg',
        'description': 'A family discovers their house is larger on the inside than the outside.',
        'genres': ['horror', 'literary', 'mystery'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'House of Leaves Mark Z Danielewski',
        'published_date': '2000',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-82',
        'content_id': 'gb:seed-82',
        'title': 'Mexican Gothic',
        'author': 'Silvia Moreno-Garcia',
        'cover_url': 'https://books.google.com/books/content?id=Dt1cDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        'description': 'A glamorous socialite investigates a creepy mansion in 1950s rural Mexico.',
        'genres': ['horror', 'gothic', 'mystery'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Mexican Gothic Silvia Moreno-Garcia',
        'published_date': '2020',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-700',
        'content_id': 'gb:seed-700',
        'title': 'The Shining',
        'author': 'Stephen King',
        'cover_url': 'https://covers.openlibrary.org/b/id/12376585-L.jpg',
        'description': 'A writer takes a winter caretaker job at a haunted hotel with his family.',
        'genres': ['horror', 'psychological', 'dark'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Shining Stephen King',
        'published_date': '1977',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-701',
        'content_id': 'gb:seed-701',
        'title': 'Haunting of Hill House',
        'author': 'Shirley Jackson',
        'cover_url': 'https://covers.openlibrary.org/b/id/4289014-L.jpg',
        'description': 'Four people investigate a notoriously haunted mansion and slowly lose their minds.',
        'genres': ['horror', 'gothic', 'mystery'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Haunting of Hill House Shirley Jackson',
        'published_date': '1959',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-702',
        'content_id': 'gb:seed-702',
        'title': 'Bird Box',
        'author': 'Josh Malerman',
        'cover_url': 'https://covers.openlibrary.org/b/id/11377399-L.jpg',
        'description': 'A mother blindfolds her children to survive creatures that drive people mad on sight.',
        'genres': ['horror', 'thriller', 'survival'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Bird Box Josh Malerman',
        'published_date': '2014',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-703',
        'content_id': 'gb:seed-703',
        'title': 'Plain Bad Heroines',
        'author': 'Emily M. Danforth',
        'cover_url': 'https://covers.openlibrary.org/b/id/10332578-L.jpg',
        'description': 'A cursed all-girls school in the early 1900s mirrors dark events in the present day.',
        'genres': ['horror', 'gothic', 'literary'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Plain Bad Heroines Emily M Danforth',
        'published_date': '2020',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-704',
        'content_id': 'gb:seed-704',
        'title': 'The Terror',
        'author': 'Dan Simmons',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9781596062344-L.jpg',
        'description': 'Two ships searching for the Northwest Passage are stalked by something on the ice.',
        'genres': ['horror', 'historical fiction', 'adventure'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Terror Dan Simmons',
        'published_date': '2007',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-70',
        'content_id': 'gb:seed-70',
        'title': 'Sapiens',
        'author': 'Yuval Noah Harari',
        'cover_url': 'https://covers.openlibrary.org/b/id/8634250-L.jpg',
        'description': 'A sweeping history of humankind from the Stone Age to the Silicon Age.',
        'genres': ['non-fiction', 'history', 'science'],
        'mood': 'educational',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Sapiens Yuval Noah Harari',
        'published_date': '2011',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-71',
        'content_id': 'gb:seed-71',
        'title': 'Educated',
        'author': 'Tara Westover',
        'cover_url': 'https://covers.openlibrary.org/b/id/8314077-L.jpg',
        'description': 'A woman raised by survivalists in the mountains escapes to earn a Cambridge PhD.',
        'genres': ['memoir', 'non-fiction', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Educated Tara Westover',
        'published_date': '2018',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-72',
        'content_id': 'gb:seed-72',
        'title': 'The Immortal Life of Henrietta Lacks',
        'author': 'Rebecca Skloot',
        'cover_url': 'https://covers.openlibrary.org/b/id/8364866-L.jpg',
        'description': "A Black woman's cancer cells were taken without consent and changed medicine forever.",
        'genres': ['non-fiction', 'science', 'biography'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Immortal Life of Henrietta Lacks Rebecca Skloot',
        'published_date': '2010',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-73',
        'content_id': 'gb:seed-73',
        'title': "Man's Search for Meaning",
        'author': 'Viktor Frankl',
        'cover_url':'https://covers.openlibrary.org/b/id/12627383-M.jpg',
        'description': 'A psychiatrist finds purpose inside Nazi concentration camps through logotherapy.',
        'genres': ['memoir', 'philosophy', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': "Man's Search for Meaning Viktor Frankl",
        'published_date': '1946',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-74',
        'content_id': 'gb:seed-74',
        'title': 'Atomic Habits',
        'author': 'James Clear',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/2035969204-L.jpg',
        'description': 'A practical framework for building good habits and breaking bad ones.',
        'genres': ['self-help', 'non-fiction', 'psychology'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Atomic Habits James Clear',
        'published_date': '2018',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-800',
        'content_id': 'gb:seed-800',
        'title': 'The Power of Now',
        'author': 'Eckhart Tolle',
        'cover_url': 'https://covers.openlibrary.org/b/id/551262-L.jpg',
        'description': 'A spiritual guide to living fully in the present moment.',
        'genres': ['self-help', 'spirituality', 'philosophy'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Power of Now Eckhart Tolle',
        'published_date': '1997',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-801',
        'content_id': 'gb:seed-801',
        'title': 'Thinking Fast and Slow',
        'author': 'Daniel Kahneman',
        'cover_url': 'https://covers.openlibrary.org/b/id/13290711-L.jpg',
        'description': 'A Nobel laureate explores the two systems that drive how we think and decide.',
        'genres': ['non-fiction', 'psychology', 'science'],
        'mood': 'educational',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Thinking Fast and Slow Daniel Kahneman',
        'published_date': '2011',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-802',
        'content_id': 'gb:seed-802',
        'title': 'The Body Keeps the Score',
        'author': 'Bessel van der Kolk',
        'cover_url': 'https://covers.openlibrary.org/b/id/8315367-L.jpg',
        'description': 'How trauma reshapes the brain and body and what can heal it.',
        'genres': ['non-fiction', 'psychology', 'science'],
        'mood': 'educational',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Body Keeps the Score Bessel van der Kolk',
        'published_date': '2014',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-803',
        'content_id': 'gb:seed-803',
        'title': 'Quiet',
        'author': 'Susan Cain',
        'cover_url': 'https://covers.openlibrary.org/b/id/7079753-L.jpg',
        'description': 'The power of introverts in a world that cannot stop talking.',
        'genres': ['non-fiction', 'psychology', 'self-help'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Quiet Susan Cain',
        'published_date': '2012',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-804',
        'content_id': 'gb:seed-804',
        'title': 'The Subtle Art of Not Giving a F*ck',
        'author': 'Mark Manson',
        'cover_url': 'https://covers.openlibrary.org/b/id/8231990-L.jpg',
        'description': 'A counterintuitive approach to living a good life by choosing what matters.',
        'genres': ['self-help', 'non-fiction', 'philosophy'],
        'mood': 'funny',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Subtle Art of Not Giving a Fck Mark Manson',
        'published_date': '2016',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-805',
        'content_id': 'gb:seed-805',
        'title': 'Born a Crime',
        'author': 'Trevor Noah',
        'cover_url': 'https://covers.openlibrary.org/b/id/10395542-M.jpg',
        'description': 'Trevor Noah grows up mixed-race in apartheid South Africa with dark humour.',
        'genres': ['memoir', 'biography', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Born a Crime Trevor Noah',
        'published_date': '2016',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-806',
        'content_id': 'gb:seed-806',
        'title': 'The Diary of a Young Girl',
        'author': 'Anne Frank',
        'cover_url': 'https://covers.openlibrary.org/b/id/8584021-L.jpg',
        'description': "Anne Frank's journal written while hiding from the Nazis in Amsterdam.",
        'genres': ['memoir', 'biography', 'historical'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Diary of a Young Girl Anne Frank',
        'published_date': '1947',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-807',
        'content_id': 'gb:seed-807',
        'title': 'Becoming',
        'author': 'Michelle Obama',
        'cover_url': 'https://covers.openlibrary.org/b/id/8824664-L.jpg',
        'description': "Michelle Obama's memoir about growing up on the South Side of Chicago.",
        'genres': ['memoir', 'biography', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Becoming Michelle Obama',
        'published_date': '2018',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-808',
        'content_id': 'gb:seed-808',
        'title': 'The Tipping Point',
        'author': 'Malcolm Gladwell',
        'cover_url': 'https://covers.openlibrary.org/b/id/10873292-L.jpg',
        'description': 'How little things can make a big difference and ideas spread like epidemics.',
        'genres': ['non-fiction', 'psychology', 'social science'],
        'mood': 'educational',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Tipping Point Malcolm Gladwell',
        'published_date': '2000',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-900',
        'content_id': 'gb:seed-900',
        'title': 'All the Light We Cannot See',
        'author': 'Anthony Doerr',
        'cover_url': 'https://covers.openlibrary.org/b/id/14559680-L.jpg',
        'description': "A blind French girl and a German soldier's fates intersect in occupied France.",
        'genres': ['historical fiction', 'war', 'literary'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'All the Light We Cannot See Anthony Doerr',
        'published_date': '2014',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-901',
        'content_id': 'gb:seed-901',
        'title': 'The Book Thief',
        'author': 'Markus Zusak',
        'cover_url': 'https://covers.openlibrary.org/b/id/8153054-L.jpg',
        'description': 'A girl in Nazi Germany steals books and shares them with people in her basement.',
        'genres': ['historical fiction', 'war', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Book Thief Markus Zusak',
        'published_date': '2005',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-902',
        'content_id': 'gb:seed-902',
        'title': 'Pillars of the Earth',
        'author': 'Ken Follett',
        'cover_url': 'https://covers.openlibrary.org/b/id/9269909-L.jpg',
        'description': 'The building of a cathedral in 12th century England weaves together lives and power.',
        'genres': ['historical fiction', 'epic', 'adventure'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Pillars of the Earth Ken Follett',
        'published_date': '1989',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-903',
        'content_id': 'gb:seed-903',
        'title': 'Wolf Hall',
        'author': 'Hilary Mantel',
        'cover_url': 'https://covers.openlibrary.org/b/id/8345848-L.jpg',
        'description': 'Thomas Cromwell rises to power in the court of Henry VIII.',
        'genres': ['historical fiction', 'political', 'literary'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Wolf Hall Hilary Mantel',
        'published_date': '2009',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-904',
        'content_id': 'gb:seed-904',
        'title': 'Lincoln in the Bardo',
        'author': 'George Saunders',
        'cover_url': 'https://covers.openlibrary.org/b/id/7909378-L.jpg',
        'description': 'Abraham Lincoln grieves his dead son while ghosts in a cemetery grapple with death.',
        'genres': ['historical fiction', 'literary', 'fantasy'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'Lincoln in the Bardo George Saunders',
        'published_date': '2017',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-905',
        'content_id': 'gb:seed-905',
        'title': 'The Name of the Rose',
        'author': 'Umberto Eco',
        'cover_url': 'https://covers.openlibrary.org/b/id/8598263-L.jpg',
        'description': 'A monk investigates a series of murders in a 14th century Italian monastery.',
        'genres': ['historical fiction', 'mystery', 'literary'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'google_books',
        'search_query': 'The Name of the Rose Umberto Eco',
        'published_date': '1980',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-6',
        'content_id': 'ia:prideprejudicese0000unse',
        'title': 'Pride and Prejudice',
        'author': 'Jane Austen',
        'cover_url': 'https://covers.openlibrary.org/b/id/12521160-M.jpg',
        'description': 'Elizabeth Bennet and the proud Mr Darcy navigate love and class in Regency England.',
        'genres': ['romance', 'literary', 'classic'],
        'mood': 'romantic',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Pride and Prejudice Jane Austen',
        'published_date': '1813',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/prideandprejudic00austuoft',
    },
    {
        'id': 'seed-7',
        'content_id': 'ia:isbn_9781105416194',
        'title': 'Frankenstein',
        'author': 'Mary Shelley',
        'cover_url': 'https://covers.openlibrary.org/b/id/12356249-L.jpg',
        'description': 'A scientist creates life from dead matter and must face the consequences.',
        'genres': ['horror', 'gothic', 'philosophical'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Frankenstein Mary Shelley',
        'published_date': '1818',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/frankensteinormo00shel',
    },
    {
        'id': 'seed-13',
        'content_id': 'ia:ERIC_EJ1068441',
        'title': 'Moby Dick',
        'author': 'Herman Melville',
        'cover_url': 'https://covers.openlibrary.org/b/id/10544254-L.jpg',
        'description': "Captain Ahab's all-consuming obsession with hunting the white whale.",
        'genres': ['literary', 'adventure', 'classic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Moby Dick Herman Melville',
        'published_date': '1851',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/mobydickorwhale01melv',
    },
    {
        'id': 'seed-90',
        'content_id': 'ia:edmonddantesseq00dumagoog',
        'title': 'The Count of Monte Cristo',
        'author': 'Alexandre Dumas',
        'cover_url': 'https://covers.openlibrary.org/b/id/14566393-L.jpg',
        'description': 'A man wrongly imprisoned escapes to exact elaborate revenge on his enemies.',
        'genres': ['adventure', 'literary', 'classic'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'The Count of Monte Cristo Alexandre Dumas',
        'published_date': '1844',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/countofmontecris01duma',
    },
    {
        'id': 'seed-91',
        'content_id': 'ia:adventuresofhuck0000mark_h4o0',
        'title': 'Adventures of Huckleberry Finn',
        'author': 'Mark Twain',
        'cover_url': 'https://covers.openlibrary.org/b/id/8157718-L.jpg',
        'description': 'A boy and a runaway slave journey down the Mississippi River to freedom.',
        'genres': ['adventure', 'literary', 'classic'],
        'mood': 'adventurous',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Adventures of Huckleberry Finn Mark Twain',
        'published_date': '1884',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/adventuresofhuck00twai',
    },
    {
        'id': 'seed-92',
        'content_id': 'ia:bwb_S0-ATS-526',
        'title': 'Dracula',
        'author': 'Bram Stoker',
        'cover_url': 'https://covers.openlibrary.org/b/id/12216503-L.jpg',
        'description': 'A Transylvanian vampire comes to England and a band of heroes must stop him.',
        'genres': ['horror', 'gothic', 'classic'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Dracula Bram Stoker',
        'published_date': '1897',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/dracula00stok',
    },
    {
        'id': 'seed-93',
        'content_id': 'ia:bwb_S0-BQE-440',
        'title': 'The Picture of Dorian Gray',
        'author': 'Oscar Wilde',
        'cover_url': 'https://covers.openlibrary.org/b/id/14314858-L.jpg',
        'description': 'A vain young man trades his soul to stay beautiful while his portrait ages.',
        'genres': ['literary', 'gothic', 'philosophical'],
        'mood': 'dark',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'The Picture of Dorian Gray Oscar Wilde',
        'published_date': '1890',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/pictureofdoriang00wild',
    },
    {
        'id': 'seed-94',
        'content_id': 'ia:bwb_Y0-CHZ-266',
        'title': 'War and Peace',
        'author': 'Leo Tolstoy',
        'cover_url': 'https://covers.openlibrary.org/b/id/12621906-L.jpg',
        'description': "Five aristocratic families navigate love and loss during Napoleon's invasion of Russia.",
        'genres': ['literary', 'historical fiction', 'epic', 'classic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'War and Peace Leo Tolstoy',
        'published_date': '1869',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/warandpeace00tolsuoft',
    },
    {
        'id': 'seed-95',
        'content_id': 'ia:seed-95',
        'title': 'The Brothers Karamazov',
        'author': 'Fyodor Dostoevsky',
        'cover_url': 'https://covers.openlibrary.org/b/id/8272336-L.jpg',
        'description': 'Three brothers wrestle with faith, doubt, and guilt after their father is murdered.',
        'genres': ['literary', 'philosophical', 'classic'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'The Brothers Karamazov Dostoevsky',
        'published_date': '1880',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/brotherskaramazo00dost',
    },
    {
        'id': 'seed-96',
        'content_id': 'ia:seed-96',
        'title': 'Don Quixote',
        'author': 'Miguel de Cervantes',
        'cover_url': 'https://covers.openlibrary.org/b/id/14428305-L.jpg',
        'description': "A man driven mad by chivalric romances sets out as a knight to right the world's wrongs.",
        'genres': ['literary', 'adventure', 'comedy', 'classic'],
        'mood': 'funny',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Don Quixote Miguel de Cervantes',
        'published_date': '1605',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/donquixote00cerv',
    },
    {
        'id': 'seed-97',
        'content_id': 'ia:seed-97',
        'title': 'Great Expectations',
        'author': 'Charles Dickens',
        'cover_url': 'https://covers.openlibrary.org/b/id/13322313-L.jpg',
        'description': 'An orphan boy named Pip grows up dreaming of becoming a gentleman.',
        'genres': ['literary', 'coming-of-age', 'classic'],
        'mood': 'thoughtful',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Great Expectations Charles Dickens',
        'published_date': '1861',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/greatexpectation00dick',
    },
    {
        'id': 'seed-98',
        'content_id': 'ia:seed-98',
        'title': 'The Odyssey',
        'author': 'Homer',
        'cover_url': 'https://covers.openlibrary.org/b/id/9045853-L.jpg',
        'description': 'Odysseus spends ten years trying to return home after the fall of Troy.',
        'genres': ['adventure', 'mythology', 'classic', 'epic'],
        'mood': 'epic',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'The Odyssey Homer',
        'published_date': '800BC',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/odyssey00home',
    },
    {
        'id': 'seed-99',
        'content_id': 'ia:seed-99',
        'title': 'Sherlock Holmes',
        'author': 'Arthur Conan Doyle',
        'cover_url': 'https://covers.openlibrary.org/b/id/6717853-L.jpg',
        'description': "The world's greatest detective solves London's most baffling crimes.",
        'genres': ['mystery', 'adventure', 'classic'],
        'mood': 'mysterious',
        'content_type': 'book',
        'source': 'internet_archive',
        'search_query': 'Adventures of Sherlock Holmes Arthur Conan Doyle',
        'published_date': '1892',
        'is_public_domain': True,
        'is_free': True,
        'free_url': 'https://archive.org/details/adventuresofsher00doyl',
    },
    {
        'id': 'seed-8',
        'content_id': 'cv:seed-8',
        'title': 'Saga',
        'author': 'Brian K. Vaughan',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/1607066017-L.jpg',
        'description': 'Two soldiers from opposite sides of a galactic war raise a child on the run.',
        'genres': ['sci-fi', 'comics', 'adventure'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Saga Brian K Vaughan',
        'published_date': '2012',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-12',
        'content_id': 'cv:seed-12',
        'title': 'Maus',
        'author': 'Art Spiegelman',
        'cover_url': 'https://covers.openlibrary.org/b/id/10210168-L.jpg',
        'description': "Art Spiegelman's father recounts surviving the Holocaust, told with mice and cats.",
        'genres': ['biography', 'history', 'comics', 'dark'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Maus Art Spiegelman',
        'published_date': '1991',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-100',
        'content_id': 'cv:seed-100',
        'title': 'Watchmen',
        'author': 'Alan Moore',
        'cover_url': 'https://covers.openlibrary.org/b/id/7774899-L.jpg',
        'description': 'Retired superheroes investigate a murder in a world that outlawed them.',
        'genres': ['comics', 'mystery', 'dark', 'political'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Watchmen Alan Moore',
        'published_date': '1987',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-101',
        'content_id': 'cv:seed-101',
        'title': 'Sandman',
        'author': 'Neil Gaiman',
        'cover_url': 'https://covers.openlibrary.org/b/id/7508162-L.jpg',
        'description': 'The lord of dreams escapes captivity after 70 years and must rebuild his realm.',
        'genres': ['comics', 'fantasy', 'mythology', 'dark'],
        'mood': 'fantastical',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Sandman Neil Gaiman',
        'published_date': '1989',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-102',
        'content_id': 'cv:seed-102',
        'title': 'Persepolis',
        'author': 'Marjane Satrapi',
        'cover_url': 'https://covers.openlibrary.org/b/id/12648921-L.jpg',
        'description': 'A young girl comes of age during the Iranian Revolution and its aftermath.',
        'genres': ['comics', 'memoir', 'biography', 'inspiring'],
        'mood': 'inspiring',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Persepolis Marjane Satrapi',
        'published_date': '2000',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-103',
        'content_id': 'cv:seed-103',
        'title': 'Batman Year One',
        'author': 'Frank Miller',
        'cover_url': 'https://covers.openlibrary.org/b/id/798170-L.jpg',
        'description': 'Bruce Wayne and James Gordon both begin their careers in a corrupt Gotham City.',
        'genres': ['comics', 'crime', 'adventure', 'dark'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Batman Year One Frank Miller',
        'published_date': '1987',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-104',
        'content_id': 'cv:seed-104',
        'title': 'V for Vendetta',
        'author': 'Alan Moore',
        'cover_url': 'https://covers.openlibrary.org/b/id/12293384-L.jpg',
        'description': 'A masked anarchist fights a fascist government in a dystopian future Britain.',
        'genres': ['comics', 'political', 'dystopia', 'dark'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'V for Vendetta Alan Moore',
        'published_date': '1988',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-105',
        'content_id': 'cv:seed-105',
        'title': 'Bone',
        'author': 'Jeff Smith',
        'cover_url': 'https://covers.openlibrary.org/b/id/12648893-L.jpg',
        'description': 'Three cartoon cousins are lost in a vast valley full of monsters and mysteries.',
        'genres': ['comics', 'fantasy', 'adventure', 'funny'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Bone Jeff Smith',
        'published_date': '1991',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-106',
        'content_id': 'cv:seed-106',
        'title': 'Preacher',
        'author': 'Garth Ennis',
        'cover_url': 'https://covers.openlibrary.org/b/id/798084-L.jpg',
        'description': 'A Texas preacher with a supernatural power hunts God across America.',
        'genres': ['comics', 'adventure', 'dark', 'funny'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Preacher Garth Ennis',
        'published_date': '1995',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-107',
        'content_id': 'cv:seed-107',
        'title': 'Y The Last Man',
        'author': 'Brian K. Vaughan',
        'cover_url': 'https://covers.openlibrary.org/b/id/798859-L.jpg',
        'description': 'Every mammal with a Y chromosome dies suddenly except one man and his monkey.',
        'genres': ['comics', 'sci-fi', 'adventure'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Y The Last Man Brian K Vaughan',
        'published_date': '2002',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-108',
        'content_id': 'cv:seed-108',
        'title': 'From Hell',
        'author': 'Alan Moore',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9788186939024-L.jpg',
        'description': 'A meticulous retelling of the Jack the Ripper murders in Victorian London.',
        'genres': ['comics', 'historical fiction', 'mystery', 'dark'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'From Hell Alan Moore',
        'published_date': '1989',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-109',
        'content_id': 'cv:seed-109',
        'title': 'Fables',
        'author': 'Bill Willingham',
        'cover_url': 'https://covers.openlibrary.org/b/id/12845484-L.jpg',
        'description': 'Fairy tale characters have been exiled to live secretly in modern New York City.',
        'genres': ['comics', 'fantasy', 'adventure', 'mystery'],
        'mood': 'fantastical',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Fables Bill Willingham',
        'published_date': '2002',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-110',
        'content_id': 'cv:seed-110',
        'title': 'Transmetropolitan',
        'author': 'Warren Ellis',
        'cover_url': 'https://covers.openlibrary.org/b/id/883146-L.jpg',
        'description': 'A gonzo journalist exposes corruption in a depraved far-future city.',
        'genres': ['comics', 'sci-fi', 'political', 'funny'],
        'mood': 'funny',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Transmetropolitan Warren Ellis',
        'published_date': '1997',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-111',
        'content_id': 'cv:seed-111',
        'title': 'The Walking Dead',
        'author': 'Robert Kirkman',
        'cover_url': 'https://covers.openlibrary.org/b/id/844763-L.jpg',
        'description': "A sheriff's deputy leads a group of survivors through a zombie apocalypse.",
        'genres': ['comics', 'horror', 'adventure', 'dark'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'The Walking Dead Robert Kirkman',
        'published_date': '2003',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-112',
        'content_id': 'cv:seed-112',
        'title': 'Invincible',
        'author': 'Robert Kirkman',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/1106900154-L.jpg',
        'description': 'A teenager inherits superpowers from his father but discovers a dark secret.',
        'genres': ['comics', 'superhero', 'adventure', 'dark'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Invincible Robert Kirkman',
        'published_date': '2003',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-113',
        'content_id': 'cv:seed-113',
        'title': 'Black Panther',
        'author': 'Ta-Nehisi Coates',
        'cover_url': 'https://covers.openlibrary.org/b/id/10624588-L.jpg',
        'description': 'The king of Wakanda fights to protect his nation from threats within and without.',
        'genres': ['comics', 'superhero', 'political', 'adventure'],
        'mood': 'epic',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Black Panther Ta-Nehisi Coates',
        'published_date': '2016',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-114',
        'content_id': 'cv:seed-114',
        'title': 'Ms Marvel',
        'author': 'G. Willow Wilson',
        'cover_url': 'https://covers.openlibrary.org/b/id/8796616-L.jpg',
        'description': 'A Pakistani-American Muslim teenager from New Jersey discovers she has superpowers.',
        'genres': ['comics', 'superhero', 'coming-of-age', 'funny'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Ms Marvel Kamala Khan',
        'published_date': '2014',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-115',
        'content_id': 'cv:seed-115',
        'title': 'Hawkeye',
        'author': 'Matt Fraction',
        'cover_url': 'https://covers.openlibrary.org/b/id/7855585-L.jpg',
        'description': 'What does Hawkeye do when he is not being an Avenger? Gets into trouble.',
        'genres': ['comics', 'superhero', 'funny', 'crime'],
        'mood': 'funny',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Hawkeye Matt Fraction',
        'published_date': '2012',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-116',
        'content_id': 'cv:seed-116',
        'title': 'Locke and Key',
        'author': 'Joe Hill',
        'cover_url': 'https://covers.openlibrary.org/b/id/6671226-L.jpg',
        'description': 'Three siblings move into their ancestral home and discover magical keys.',
        'genres': ['comics', 'horror', 'fantasy', 'mystery'],
        'mood': 'mysterious',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Locke and Key Joe Hill',
        'published_date': '2008',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-117',
        'content_id': 'cv:seed-117',
        'title': 'East of West',
        'author': 'Jonathan Hickman',
        'cover_url': 'https://covers.openlibrary.org/b/id/12750523-L.jpg',
        'description': 'Death rides through an alternate America where the apocalypse is a political conspiracy.',
        'genres': ['comics', 'sci-fi', 'dark', 'political'],
        'mood': 'dark',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'East of West Jonathan Hickman',
        'published_date': '2013',
        'is_free': False,
        'free_url': None,
    },
    {
        'id': 'seed-118',
        'content_id': 'cv:seed-118',
        'title': 'Paper Girls',
        'author': 'Brian K. Vaughan',
        'cover_url': 'https://covers.openlibrary.org/b/id/10456615-L.jpg',
        'description': 'Four newspaper delivery girls stumble into a time war in 1980s Ohio.',
        'genres': ['comics', 'sci-fi', 'adventure', 'mystery'],
        'mood': 'adventurous',
        'content_type': 'comic',
        'source': 'comic_vine',
        'search_query': 'Paper Girls Brian K Vaughan',
        'published_date': '2015',
        'is_free': False,
        'free_url': None,
    },
]

# Fast memory index for instant ID resolution across all key formats
_CATALOG_BY_ID: dict[str, dict[str, Any]] = {}
for item in _CATALOG_SEED:
    if item.get("id"):
        _CATALOG_BY_ID[str(item["id"])] = item
    if item.get("content_id"):
        cid = str(item["content_id"])
        _CATALOG_BY_ID[cid] = item
        if ":" in cid:
            _CATALOG_BY_ID[cid.split(":", 1)[1]] = item


import urllib.parse


from urllib.parse import quote, unquote

def optimize_cover_url(url: str | None, width: int = 260) -> str | None:
    """Normalize and optimize cover URLs across Google, Comic Vine, IA, and Open Library."""
    if not url or not isinstance(url, str):
        return None

    url = url.strip()
    if not url:
        return None

    # 1. Unwrap pre-existing wsrv.nl proxy wrappers to avoid double proxying
    if "wsrv.nl/?url=" in url or "wsrv.nl?" in url:
        parts = url.split("url=")
        if len(parts) > 1:
            url = unquote(parts[-1].split("&")[0])

    # 2. Force HTTPS
    if url.startswith("http://"):
        url = "https://" + url[7:]

    # 3. GOOGLE BOOKS: Direct fetch (Google blocks proxy scrapers with 403)
    if "books.google.com" in url or "googleusercontent.com" in url:
        if "edge=curl" in url:
            url = url.replace("edge=curl", "")
        return url

    # 4. COMIC VINE: Direct fetch (Comic Vine WAF blocks wsrv.nl proxy with 403 Forbidden)
    if "comicvine.gamespot.com" in url or "static.comicvine.com" in url or "cbsistatic.com" in url:
        return url

    # 5. INTERNET ARCHIVE, OPEN LIBRARY, & OTHERS:
    # Route through Cloudflare Edge CDN (wsrv.nl) -> converts heavy PNG/JPG into ~15KB WebP
    encoded_target = quote(url, safe="")
    return f"https://wsrv.nl/?url={encoded_target}&w={width}&output=webp"


def _card_summary(item: dict[str, Any]) -> dict[str, Any]:
    """Extract lightweight card fields for Home feed (reduces JSON payload size by 90%)."""
    raw_cover = item.get("cover_url", "") or ""
    optimized_cover = optimize_cover_url(raw_cover, width=300)

    author = item.get("author")
    authors = item.get("authors", [])
    if not author and authors:
        author = authors[0] if isinstance(authors, list) else str(authors)

    cid = item.get("content_id") or item.get("id") or ""

    return {
        "content_id": str(cid),
        "id": str(cid),
        "title": item.get("title", "Unknown"),
        "author": author or "Unknown Author",
        "cover_url": optimized_cover,
        "content_type": item.get("content_type", "book"),
        "is_free": bool(item.get("is_free", False)),
        "free_url": item.get("free_url"),
        "source": item.get("source", "google_books"),
        "genres": item.get("genres", []),
    }
def _source_prefix(external_source: str) -> str:
    if external_source == SOURCE_COMIC_VINE:
        return "cv"
    if external_source == SOURCE_INTERNET_ARCHIVE:
        return "ia"
    return "gb"


def _collections_cache_key(
    user_id: str | None,
    content_preference: str,
    n_collections: int,
    row_limit: int,
    ratings_fingerprint: str,
) -> str:
    who = "anon" if user_id is None else f"u:{user_id}:{ratings_fingerprint}"
    return f"collections:v3:{who}:{content_preference}:{n_collections}:{row_limit}"


def _ratings_fingerprint(user_ratings: list[dict[str, Any]]) -> str:
    if not user_ratings:
        return "no-ratings"
    parts = sorted(
        f"{r.get('content_id', '')}:{r.get('rating', '')}"
        for r in user_ratings
    )
    return hashlib.md5("|".join(parts).encode("utf-8")).hexdigest()[:10]


async def _get_optional_user(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
    db: AsyncSession = Depends(get_db),
) -> User | None:
    if credentials is None:
        return None

    user_id_str = verify_token(credentials.credentials, expected_type="access")
    if user_id_str is None:
        return None

    try:
        from uuid import UUID
        user_id = UUID(user_id_str)
    except ValueError:
        return None

    return await get_by_id(db, user_id)


@router.get(
    "/api/v1/collections",
    status_code=status.HTTP_200_OK,
)
async def get_collections(
    request: Request,
    n_collections: int = Query(default=20, ge=1, le=30),
    row_limit: int = Query(default=20, ge=1, le=50),
    current_user: User | None = Depends(_get_optional_user),
    db: AsyncSession = Depends(get_db),
    content_router: ContentRouter = Depends(get_content_router),
) -> dict[str, Any]:
    """Return themed collection rows for the home screen (Instant Load)."""
    user_id: str | None = None
    user_ratings: list[dict[str, Any]] = []
    content_preference = "both"

    if current_user is not None:
        user_id = str(current_user.id)

        ratings_result, _ = await get_ratings_by_user(
            db,
            user_id=current_user.id,
            limit=100,
            offset=0,
        )

        for r in ratings_result:
            if r.book is None:
                continue
            prefix = _source_prefix(r.book.external_source)
            content_id = f"{prefix}:{r.book.external_id}"
            user_ratings.append({
                "user_id": str(current_user.id),
                "content_id": content_id,
                "rating": float(r.rating),
                "title": r.book.title,
            })

        prefs = await get_preferences(db, user_id=current_user.id)
        if prefs is not None and hasattr(prefs, "content_type_preference"):
            content_preference = getattr(prefs, "content_type_preference", "both")

    fingerprint = _ratings_fingerprint(user_ratings)
    response_cache_key = _collections_cache_key(
        user_id=user_id,
        content_preference=content_preference,
        n_collections=n_collections,
        row_limit=row_limit,
        ratings_fingerprint=fingerprint,
    )

    cached_response = await redis_client.get(response_cache_key)
    if isinstance(cached_response, dict) and "rows" in cached_response and len(cached_response["rows"]) > 0:
        return success_envelope(cached_response)

    # Build rows with ML/Clustering engine
    service = CollectionService()
    raw_rows = service.build_home_screen(
        catalog=_CATALOG_SEED,
        user_id=user_id,
        user_ratings=user_ratings,
        content_preference=content_preference,
        n_collections=n_collections,
        row_limit=row_limit,
    )

    # Instant In-Memory Item Resolution with Lightweight Card Formatting
    final_rows: list[dict[str, Any]] = []
    for row in raw_rows:
        row_items: list[dict[str, Any]] = []
        seen_ids: set[str] = set()

        for entry in row.get("items", []):
            item_data: dict[str, Any] | None = None
            if isinstance(entry, str):
                item_data = _CATALOG_BY_ID.get(entry)
            elif isinstance(entry, dict):
                eid = entry.get("content_id") or entry.get("id", "")
                base = _CATALOG_BY_ID.get(eid, {})
                item_data = {**base, **entry}

            if item_data:
                cid = item_data.get("content_id") or item_data.get("id")
                if cid and cid not in seen_ids:
                    seen_ids.add(cid)
                    row_items.append(_card_summary(item_data))

        if row_items:
            final_rows.append({
                "id": row.get("id", ""),
                "title": row.get("title", ""),
                "mood": row.get("mood", ""),
                "items": row_items,
                "item_count": len(row_items),
            })

    payload = {
        "rows": final_rows,
        "total": len(final_rows),
        "personalized": user_id is not None and len(user_ratings) > 0,
    }

    if final_rows:
        await redis_client.set(
            response_cache_key,
            payload,
            ttl_seconds=_TTL_COLLECTIONS_RESPONSE,
        )

    return success_envelope(payload)