"""initial schema

Revision ID: afdbafb6e457
Revises: 
Create Date: 2026-07-16 20:29:42.240260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afdbafb6e457'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('external_source', sa.String(length=50), server_default=sa.text("'google_books'"), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('isbn_10', sa.String(length=10), nullable=True),
    sa.Column('isbn_13', sa.String(length=13), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('cover_url_large', sa.Text(), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('ratings_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('kitabee_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('kitabee_ratings_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('average_rating BETWEEN 0 AND 5', name='books_rating_range'),
    sa.CheckConstraint('page_count > 0 OR page_count IS NULL', name='books_page_count_positive'),
    sa.CheckConstraint('published_year BETWEEN 1000 AND EXTRACT(YEAR FROM CURRENT_DATE) + 1', name='books_year_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('books_external_unique', 'books', ['external_source', 'external_id'], unique=True)
    op.create_index('idx_books_authors_gin', 'books', ['authors'], unique=False, postgresql_using='gin')
    op.create_index('idx_books_avg_rating', 'books', [sa.text('average_rating DESC')], unique=False)
    op.create_index('idx_books_cached_at', 'books', ['cached_at'], unique=False)
    op.create_index('idx_books_external', 'books', ['external_source', 'external_id'], unique=False)
    op.create_index('idx_books_genres_gin', 'books', ['genres'], unique=False, postgresql_using='gin')
    op.create_index('idx_books_isbn_13', 'books', ['isbn_13'], unique=False, postgresql_where=sa.text('isbn_13 IS NOT NULL'))
    op.create_index('idx_books_title_gin', 'books', [sa.text("to_tsvector('english', title)")], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='users_email_format'),
    sa.CheckConstraint('LENGTH(name) BETWEEN 2 AND 100', name='users_name_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='users_email_unique')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_last_login', 'users', ['last_login_at'], unique=False)
    op.create_table('library',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('want_to_read', 'currently_reading', 'read', 'dnf', name='library_status_enum'), server_default=sa.text("'want_to_read'"), nullable=False),
    sa.Column('current_page', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('started_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('current_page >= 0 AND (total_pages IS NULL OR current_page <= total_pages)', name='library_page_valid'),
    sa.CheckConstraint('finished_reading_at IS NULL OR started_reading_at IS NULL OR finished_reading_at >= started_reading_at', name='library_dates_valid'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='library_user_book_unique')
    )
    op.create_index('idx_library_added_at', 'library', [sa.text('added_at DESC')], unique=False)
    op.create_index('idx_library_book_id', 'library', ['book_id'], unique=False)
    op.create_index('idx_library_user_id', 'library', ['user_id'], unique=False)
    op.create_index('idx_library_user_status', 'library', ['user_id', 'status'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_title', sa.String(length=200), nullable=True),
    sa.Column('is_spoiler', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('LENGTH(review_text) <= 5000', name='ratings_review_length'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ratings_value_range'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='ratings_user_book_unique')
    )
    op.create_index('idx_ratings_book_id', 'ratings', ['book_id'], unique=False)
    op.create_index('idx_ratings_created_at', 'ratings', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_ratings_rating', 'ratings', ['rating'], unique=False)
    op.create_index('idx_ratings_user_book', 'ratings', ['user_id', 'book_id'], unique=False)
    op.create_index('idx_ratings_user_id', 'ratings', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.Enum('content_based', 'collaborative_knn', 'neural_cf', 'hybrid', 'trending', 'popular', name='recommendation_model_enum'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP + INTERVAL '1 hour')"), nullable=False),
    sa.CheckConstraint('rank > 0', name='recommendations_rank_positive'),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name='recommendations_score_range'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_expires', 'recommendations', ['expires_at'], unique=False)
    op.create_index('idx_recommendations_model', 'recommendations', ['model_type'], unique=False)
    op.create_index('idx_recommendations_user_rank', 'recommendations', ['user_id', 'rank'], unique=False)
    op.create_index('idx_recommendations_user_score', 'recommendations', ['user_id', sa.text('score DESC')], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('normalized_query', sa.String(length=500), nullable=False),
    sa.Column('results_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('clicked_book_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(query)) > 0', name='search_history_query_not_empty'),
    sa.ForeignKeyConstraint(['clicked_book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_history_normalized', 'search_history', ['normalized_query'], unique=False)
    op.create_index('idx_search_history_searched_at', 'search_history', [sa.text('searched_at DESC')], unique=False)
    op.create_index('idx_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('favorite_genres', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('preferred_languages', sa.ARRAY(sa.Text()), server_default=sa.text("'{en}'"), nullable=False),
    sa.Column('excluded_genres', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('content_warnings_hide', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('reading_pace', sa.String(length=20), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('preferred_book_length', sa.String(length=20), server_default=sa.text("'any'"), nullable=True),
    sa.Column('theme', sa.String(length=20), server_default=sa.text("'system'"), nullable=False),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"email": false, "push": false}\''), nullable=False),
    sa.Column('privacy_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"public_library": false, "public_ratings": false}\''), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("reading_pace IN ('slow', 'medium', 'fast')", name='user_preferences_pace_valid'),
    sa.CheckConstraint("theme IN ('light', 'dark', 'system')", name='user_preferences_theme_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='user_preferences_user_unique')
    )
    op.create_index('idx_user_preferences_genres_gin', 'user_preferences', ['favorite_genres'], unique=False, postgresql_using='gin')
    op.create_index('idx_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_preferences_user_id', table_name='user_preferences')
    op.drop_index('idx_user_preferences_genres_gin', table_name='user_preferences', postgresql_using='gin')
    op.drop_table('user_preferences')
    op.drop_index('idx_search_history_user_id', table_name='search_history')
    op.drop_index('idx_search_history_searched_at', table_name='search_history')
    op.drop_index('idx_search_history_normalized', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('idx_recommendations_user_score', table_name='recommendations')
    op.drop_index('idx_recommendations_user_rank', table_name='recommendations')
    op.drop_index('idx_recommendations_model', table_name='recommendations')
    op.drop_index('idx_recommendations_expires', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_ratings_user_id', table_name='ratings')
    op.drop_index('idx_ratings_user_book', table_name='ratings')
    op.drop_index('idx_ratings_rating', table_name='ratings')
    op.drop_index('idx_ratings_created_at', table_name='ratings')
    op.drop_index('idx_ratings_book_id', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('idx_library_user_status', table_name='library')
    op.drop_index('idx_library_user_id', table_name='library')
    op.drop_index('idx_library_book_id', table_name='library')
    op.drop_index('idx_library_added_at', table_name='library')
    op.drop_table('library')
    op.drop_index('idx_users_last_login', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_books_title_gin', table_name='books', postgresql_using='gin')
    op.drop_index('idx_books_isbn_13', table_name='books', postgresql_where=sa.text('isbn_13 IS NOT NULL'))
    op.drop_index('idx_books_genres_gin', table_name='books', postgresql_using='gin')
    op.drop_index('idx_books_external', table_name='books')
    op.drop_index('idx_books_cached_at', table_name='books')
    op.drop_index('idx_books_avg_rating', table_name='books')
    op.drop_index('idx_books_authors_gin', table_name='books', postgresql_using='gin')
    op.drop_index('books_external_unique', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
