export const rawColors = {
  canvas: "#1a1a2e",
  canvasElevated: "#252542",
  canvasSunken: "#131325",
  canvasReader: "#0d0d1a",
  canvasLight: "#f7f7f2",
  canvasLightCard: "#ffffff",
  canvasLightSunken: "#ebebeb",
  canvasLightReader: "#faf8f2",

  inkWhite: "#ffffff",
  inkReaderDark: "#e8e8f0",
  inkBodyDark: "#9e9eb8",
  inkMutedDark: "#666680",
  inkDisabledDark: "#3d3d5c",

  inkDark: "#1a1a2e",
  inkReaderLight: "#2a2a3e",
  inkBodyLight: "#4a4a6a",
  inkMutedLight: "#8888a8",
  inkDisabledLight: "#c0c0d0",

  amber: "#FFC93C",
  amberActive: "#E6A800",
  amberHover: "#D4960A",
  amberDark: "#cc8800",

  hairlineDark: "#252542",
  hairlineSubtleDark: "#1e1e38",
  hairlineStrongDark: "#3d3d5c",

  hairlineLight: "#d2d2e0",
  hairlineSubtleLight: "#ebebf0",
  hairlineStrongLight: "#b0b0c8",

  success: "#03904a",
  warning: "#f13a2c",
  info: "#4c98b9",

  overlayDark: "rgba(0,0,0,0.7)",
  overlayLight: "rgba(0,0,0,0.4)",
  chromeDark: "rgba(26,26,46,0.9)",
  chromeLight: "rgba(247,247,242,0.9)",
};

export const darkTheme = {
  background: {
    primary: rawColors.canvas,
    elevated: rawColors.canvasElevated,
    sunken: rawColors.canvasSunken,
    overlay: rawColors.overlayDark,
    card: rawColors.canvasElevated,
    input: rawColors.canvas,
    modal: rawColors.canvasElevated,
    sheet: rawColors.canvasElevated,
    toast: "#303052",
    reader: rawColors.canvasReader,
    readerChrome: rawColors.chromeDark,
  },
  text: {
    primary: rawColors.inkWhite,
    secondary: rawColors.inkBodyDark,
    muted: rawColors.inkMutedDark,
    disabled: rawColors.inkDisabledDark,
    onPrimary: rawColors.inkDark,
    link: rawColors.amber,
    placeholder: rawColors.inkMutedDark,
    reader: rawColors.inkReaderDark,
  },
  border: {
    default: rawColors.hairlineDark,
    subtle: rawColors.hairlineSubtleDark,
    strong: rawColors.hairlineStrongDark,
    focus: rawColors.amber,
    input: rawColors.hairlineDark,
    inputFocus: rawColors.amber,
    activeTab: rawColors.amber,
  },
  brand: {
    primary: rawColors.amber,
    primaryActive: rawColors.amberActive,
    primaryHover: rawColors.amberHover,
    onPrimary: rawColors.inkDark,
    semanticSuccess: rawColors.success,
    semanticWarning: rawColors.warning,
    semanticInfo: rawColors.info,
    freeReading: rawColors.amber,
  },
};

export const lightTheme = {
  background: {
    primary: rawColors.canvasLight,
    elevated: rawColors.canvasLightCard,
    sunken: rawColors.canvasLightSunken,
    overlay: rawColors.overlayLight,
    card: rawColors.canvasLightCard,
    input: rawColors.canvasLightCard,
    modal: rawColors.canvasLightCard,
    sheet: rawColors.canvasLightCard,
    toast: rawColors.inkDark,
    reader: rawColors.canvasLightReader,
    readerChrome: rawColors.chromeLight,
  },
  text: {
    primary: rawColors.inkDark,
    secondary: rawColors.inkBodyLight,
    muted: rawColors.inkMutedLight,
    disabled: rawColors.inkDisabledLight,
    onPrimary: rawColors.inkDark,
    link: rawColors.amberDark,
    placeholder: rawColors.inkMutedLight,
    reader: rawColors.inkReaderLight,
  },
  border: {
    default: rawColors.hairlineLight,
    subtle: rawColors.hairlineSubtleLight,
    strong: rawColors.hairlineStrongLight,
    focus: rawColors.amber,
    input: rawColors.hairlineLight,
    inputFocus: rawColors.amber,
    activeTab: rawColors.amber,
  },
  brand: {
    primary: rawColors.amber,
    primaryActive: rawColors.amberActive,
    primaryHover: rawColors.amberHover,
    onPrimary: rawColors.inkDark,
    semanticSuccess: rawColors.success,
    semanticWarning: rawColors.warning,
    semanticInfo: rawColors.info,
    freeReading: rawColors.amber,
  },
};

export type Theme = typeof darkTheme;